from copy import copy
from settings.BaseConfiguration import Configuration
from teams_four.ArgentiBronyaPelaHuohuo import ArgentiBronyaPelaHuohuo
from teams_four.ArgentiHanyaRuanMeiHuohuo import ArgentiHanyaRuanMeiHuohuo
from teams_four.ArgentiHanyaTingyunFuxuan import ArgentiHanyaTingyunFuxuan
from teams_four.ArgentiHanyaTingyunHuohuo import ArgentiHanyaTingyunHuohuo
from teams_four.ArgentiRuanMeiTingyunHuohuo import ArgentiRuanMeiTingyunHuohuo
from teams_four.BladeBronyaPelaFuxuan import BladeBronyaPelaFuxuan
from teams_four.BladeBronyaPelaLuocha import BladeBronyaPelaLuocha
from teams_four.BladeBronyaPelaLynx import BladeBronyaPelaLynx
from teams_four.BladeBronyaRuanMeiFuxuan import BladeBronyaRuanMeiFuxuan
from teams_four.BladeBronyaRuanMeiLuocha import BladeBronyaRuanMeiLuocha
from teams_four.ClaraSilverWolfPelaLuocha import ClaraSilverWolfPelaLuocha
from teams_four.ClaraTingyunPelaLuocha import ClaraTingyunPelaLuocha
from teams_four.ClaraTingyunTopazLuocha import ClaraTingyunTopazLuocha
from teams_four.ClaraTopazAstaLuocha import ClaraTopazAstaLuocha
from teams_four.ClaraTopazHanyaLuocha import ClaraTopazHanyaLuocha
from teams_four.JingliuBronyaPelaLuocha import JingliuBronyaPelaLuocha
from teams_four.JingliuBronyaRuanMeiLuocha import JingliuBronyaRuanMeiLuocha
from teams_four.JingliuHanyaBladeHuohuo import JingliuHanyaBladeHuohuo
from teams_four.JingliuRuanMeiBladeLuocha import JingliuRuanMeiBladeLuocha
from teams_four.JingyuanTingyunAstaLuocha import JingyuanTingyunAstaLuocha
from teams_four.JingyuanTingyunHanyaFuxuan import JingyuanTingyunHanyaFuxuan
from teams_four.JingyuanTingyunTopazLuocha import JingyuanTingyunTopazLuocha
from teams_four.KafkaGuinaifenAstaLuocha import KafkaGuinaifenAstaLuocha
from teams_four.KafkaGuinaifenHanyaLuocha import KafkaGuinaifenHanyaLuocha
from teams_four.KafkaGuinaifenLukaLuocha import KafkaGuinaifenLukaLuocha
from teams_four.KafkaGuinaifenRuanMei import KafkaGuinaifenRuanMeiLuocha
from teams_four.KafkaGuinaifenSampoLuocha import KafkaGuinaifenSampoLuocha
from teams_four.KafkaSampoRuanMei import KafkaSampoRuanMeiLuocha
from teams_four.KafkaTingyunRuanMei import KafkaTingyunRuanMeiLuocha
from teams_four.LunaeHanyaPelaLuocha import LunaeHanyaPelaLuocha
from teams_four.LunaeHanyaTingyunLuocha import LunaeHanyaTingyunLuocha
from teams_four.LunaeHanyaYukongLuocha import LunaeHanyaYukongLuocha
from teams_four.LunaePelaTingyun import LunaePelaTingyunLuocha
from teams_four.LunaePelaYukongLuocha import LunaePelaYukongLuocha
from teams_four.LunaeRuanMeiTingyun import LunaeRuanMeiTingyunLuocha
from teams_four.LunaeTingyunYukongLuocha import LunaeTingyunYukongLuocha
from teams_four.QingqueHanyaPelaFuxuan import QingqueHanyaPelaFuxuan
from teams_four.QingqueHanyaSilverWolfFuxuan import QingqueHanyaSilverWolfFuxuan
from teams_four.RatioBronyaSilverWolfLuocha import DrRatioBronyaSilverWolfLuocha
from teams_four.RatioRuanMeiSilverWolfLuocha import DrRatioRuanMeiSilverWolfLuocha
from teams_four.RatioTopazAstaLuocha import DrRatioTopazAstaLuocha
from teams_four.RatioHanyaSilverWolfLuocha import DrRatioHanyaSilverWolfLuocha
from teams_four.RatioTopazHanyaLuocha import DrRatioTopazHanyaLuocha
from teams_four.RatioTopazRuanMeiLuocha import DrRatioTopazRuanMeiLuocha
from teams_four.SeeleMaxSilverWolfBronyaLuocha import SeeleMaxSilverWolfBronyaLuocha
from teams_four.SeeleMidSilverWolfBronyaFuxuan import SeeleMidSilverWolfBronyaFuxuan
from teams_four.SeeleMidSilverWolfBronyaLuocha import SeeleMidSilverWolfBronyaLuocha
from teams_four.TopazTingyunHanyaLuocha import TopazTingyunHanyaLuocha
from teams_four.XueyiHanyaPelaFuxuan import XueyiHanyaPelaFuxuan
from visualizer.visualizer import visualize

visualizationList = []

config = copy(Configuration)
config['numEnemies'] = 2
config['enemySpeed'] = 132 / 1.125 # assume 25% action delay every 2 enemy turns from toughness break

#%% Team Imports

'''
visualizationList.append(ArgentiHanyaRuanMeiHuohuo(config))
visualizationList.append(ArgentiRuanMeiTingyunHuohuo(config))
visualizationList.append(ArgentiHanyaTingyunHuohuo(config))
#visualizationList.append(ArgentiHanyaTingyunFuxuan(config))
#visualizationList.append(ArgentiBronyaPelaHuohuo(config))
visualizationList.append(BladeBronyaPelaFuxuan(config))
#visualizationList.append(BladeBronyaRuanMeiFuxuan(config))
visualizationList.append(BladeBronyaPelaLuocha(config))
visualizationList.append(BladeBronyaRuanMeiLuocha(config))
#visualizationList.append(BladeBronyaPelaLynx(config))
#visualizationList.append(ClaraSilverWolfPelaLuocha(config))
#visualizationList.append(ClaraTingyunPelaLuocha(config))
#visualizationList.append(ClaraTingyunTopazLuocha(config))
visualizationList.append(ClaraTopazAstaLuocha(config))
visualizationList.append(DrRatioTopazAstaLuocha(config))
visualizationList.append(DrRatioTopazRuanMeiLuocha(config))
visualizationList.append(DrRatioTopazHanyaLuocha(config))
visualizationList.append(DrRatioHanyaSilverWolfLuocha(config))
visualizationList.append(DrRatioRuanMeiSilverWolfLuocha(config))
#visualizationList.append(DrRatioBronyaSilverWolfLuocha(config))
#visualizationList.append(ClaraTopazHanyaLuocha(config))
visualizationList.append(JingliuBronyaPelaLuocha(config))
visualizationList.append(JingliuBronyaRuanMeiLuocha(config))
visualizationList.append(JingliuRuanMeiBladeLuocha(config))
#visualizationList.append(JingliuHanyaBladeHuohuo(config))
#visualizationList.append(JingyuanTingyunAstaLuocha(config))
visualizationList.append(JingyuanTingyunHanyaFuxuan(config))
#visualizationList.append(JingyuanTingyunTopazLuocha(config))
#visualizationList.append(LunaeHanyaPelaLuocha(config))
visualizationList.append(LunaeHanyaTingyunLuocha(config))
visualizationList.append(LunaeRuanMeiTingyunLuocha(config))
#visualizationList.append(LunaePelaTingyunLuocha(config))
#visualizationList.append(LunaeHanyaYukongLuocha(config))
#visualizationList.append(LunaePelaYukongLuocha(config))
#visualizationList.append(LunaeTingyunYukongLuocha(config))'''
visualizationList.append(KafkaSampoRuanMeiLuocha(config))
visualizationList.append(KafkaGuinaifenRuanMeiLuocha(config))
visualizationList.append(KafkaTingyunRuanMeiLuocha(config))
visualizationList.append(KafkaGuinaifenAstaLuocha(config))
visualizationList.append(KafkaGuinaifenHanyaLuocha(config))
visualizationList.append(KafkaGuinaifenLukaLuocha(config))
visualizationList.append(KafkaGuinaifenSampoLuocha(config))
'''
#visualizationList.append(QingqueHanyaPelaFuxuan(config))
visualizationList.append(QingqueHanyaSilverWolfFuxuan(config))
visualizationList.append(SeeleMaxSilverWolfBronyaLuocha(config))
visualizationList.append(SeeleMidSilverWolfBronyaLuocha(config))
#visualizationList.append(SeeleMidSilverWolfBronyaFuxuan(config))
#visualizationList.append(TopazTingyunHanyaLuocha(config))
visualizationList.append(XueyiHanyaPelaFuxuan(config))
#visualizationList.append(XueyiHanyaPelaFuxuan(config,breakRatio=1.0))'''

#%% Visualization
# Visualize
visualize(visualizationList, visualizerPath='visualizer\QuadVisual.png', **config)
    
from excelAPI.write2sheet import writeVisualizationList
writeVisualizationList(visualizationList,path='visualizer\QuadVisual.xlsx',sheetname='Quad vs Two')
